spring:
  application:
    name: XiayuRoutingDatasourceApplication
server:
  port: 8083

mybatis:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/datasource_master?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
    slaveone:
      url: jdbc:mysql://127.0.0.1:3306/datasource_slave_one?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
    slavetwo:
      url: jdbc:mysql://127.0.0.1:3306/datasource_slave_two?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root