spring:
  application:
    name: XiaYuApplication
server:
  port: 8082
mybatis:
  sharding:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/multidatasource%s?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root

redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-idle: 20
    min-idle: 1
    max-active: 20
    max-wait: 6000
  database: 0
